spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: hackathon-read-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: hackathon-read-service
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: hackathon-organizer
  resource: hackathon-read-service
server:
  port: 0
