spring:
  application:
    name: hackathon-read-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/hackathon_db
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
server:
  port: 0
